name: Azure_push_v12

on:
  workflow_dispatch:
  push:
      branches: 
      - master

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v4
      
      - name: Setup .NET
        uses: action/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./Urb.Plan.v2.sln

      - name: Build
        run: dotnet build ./IES.Stock.API.sln --configuration Release --no-restore  

      - name: Publish
        run: dotnet publish ./IES.Stock.API.sln --configuration Release --no-build
